name: bake-action-36

on:
  workflow_dispatch:

env:
  GHCR_IMAGE: ghcr.io/crazy-max/buildx-buildkit-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@master
        with:
          files: |
            ./bake-action-36/docker-bake.hcl
          targets: image
          push: true
          set: |
            *.context=./bake-action-36
            *.tags=${{ env.GHCR_IMAGE }}:bake-action-36
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
