name: buildx-977

on:
  workflow_dispatch:

env:
  LOCAL_SLUG: "localhost:5000/name/app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildx-version:
          - v0.8.0-rc1
          - https://github.com/tonistiigi/buildx.git#logs-dupes
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Remove dotnet
        run: sudo rm -rf /usr/share/dotnet
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.LOCAL_SLUG }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ env.BUILDX_VERSION }}
          driver-opts: |
            network=host
          buildkitd-flags: --debug
      -
        name: Build
        uses: docker/build-push-action@master
        with:
          context: ./buildx-977
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha,scope=buildx-977
          cache-to: type=gha,scope=buildx-977,mode=max
