name: buildkit-2684

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ""
          - "app.platform=linux/amd64,linux/arm64"
          - "base.platform=linux/amd64,linux/arm64"
          - "*.platform=linux/amd64,linux/arm64"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: https://github.com/docker/buildx.git#master
          buildkitd-flags: --debug
          driver-opts: |
            image=crazymax/buildkit:2684
      -
        name: Build
        id: bake
        uses: docker/bake-action@master
        with:
          files: |
            ./buildkit-2684/docker-bake.hcl
          targets: |
            app
          set: |
            *.context=./buildkit-2684
            *.args.foo=bar
            *.args.bar=foo
            ${{ matrix.platform }}
