name: buildx-975

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: localhost:5000/name/app
  GHCR_IMAGE: ghcr.io/crazy-max/buildx-buildkit-tests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - driver: docker
            load: false
            push: true
            platforms: linux/amd64
          - driver: docker
            load: true
            push: false
            platforms: linux/amd64
          - driver: docker-container
            load: false
            push: true
            platforms: linux/amd64
          - driver: docker-container
            load: true
            push: false
            platforms: linux/amd64
          - driver: docker-container
            load: false
            push: true
            platforms: linux/amd64,linux/arm64
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: https://github.com/docker/buildx.git#master
          driver: ${{ matrix.driver }}
          driver-opts: |
            network=host
            image=moby/buildkit:master
      -
        name: Build and load
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./buildx-975
          load: ${{ matrix.load }}
          push: ${{ matrix.push }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.GHCR_IMAGE }}:buildx-975
          platforms: ${{ matrix.platforms }}
      -
        name: Docker images
        run: |
          docker image ls --no-trunc
      -
        name: Check manifest
        if: ${{ matrix.push }}
        run: |
          cat <<EOT >> metadata.json
          ${{ steps.docker_build.outputs.metadata }}
          EOT
          digest=$(cat metadata.json | jq -r '."containerimage.digest"')
          set -x
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:latest --format '{{json .}}'
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:buildx-975 --format '{{json .}}'
          docker pull ${{ env.DOCKER_IMAGE }}@$digest
      -
        name: Inspect
        if: ${{ matrix.load }}
        run: |
          set -x
          docker image inspect ${{ env.DOCKER_IMAGE }}:latest
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
