name: buildx-420

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: name/app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        driver:
          - docker
          - docker-container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: https://github.com/crazy-max/buildx.git#imageid
          driver: ${{ matrix.driver }}
          driver-opts: |
            network=host
            image=moby/buildkit:master
      -
        name: Build and load
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./buildx-420
          load: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
      -
        name: Docker images
        run: |
          docker image ls --no-trunc
      -
        name: Inspect
        run: |
          docker image inspect ${{ env.DOCKER_IMAGE }}:latest
