name: buildkit-2684

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.8.0-rc1
          driver-opts: |
            image=moby/buildkit:master
      -
        name: Build
        id: bake
        uses: docker/bake-action@master
        with:
          files: |
            ./buildkit-2684/docker-bake.hcl
          targets: |
            app
          set: |
            *.context=./buildkit-2684
            *.args.foo=bar
            *.args.bar=foo
